name: 🐛 Bug Report
description: Report something that isn't working correctly
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and how to reproduce it.
      placeholder: A clear and concise description of the issue...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      description: What did you think would happen instead?
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Add step-by-step instructions
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Library version
      placeholder: e.g., 1.0.0-beta01
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Android
        - Desktop
        - Multiplatform
        - Other
    validations:
      required: false
