# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(
        task: "jvmTest",
        project_dir: "../"
    )
  end

  desc "Take screenshots"
    lane :screenshots do
    gradle(
     task: "clean assembleDebug assembleAndroidTest",
     project_dir: "../"
    )

    screengrab(
     app_package_name: "ke.don.gondi",
     test_instrumentation_runner: "androidx.test.runner.AndroidJUnitRunner",
     app_apk_path: "../composeApp/build/outputs/apk/debug/composeApp-debug.apk",
     tests_apk_path: "../composeApp/build/outputs/apk/androidTest/debug/composeApp-debug-androidTest.apk"
    )
    end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(
        task: "clean assembleRelease",
        project_dir: "../"
    )
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(
        task: "clean assembleRelease",
        project_dir: "../"
    )
    upload_to_play_store
  end
end
