name: 📝 Append PR Template

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  append-and-label:
    runs-on: ubuntu-latest
    steps:
      - name: Append PR template and apply labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const template = `
            ## 📌 What does this PR do?
            
              <!-- Describe the purpose of this PR -->
            
              ## 🧪 How was it tested?
            
              <!-- Mention any manual/automated testing -->
            
              ## 🔨 Issue fixed
            
              <!-- Mention The issue it fixes. Prefix with '#' -->
            
              ## 🧩 Related Issues
            
              <!-- Link to related issues or discussions -->
            
            ## 📝 Checklist
            
            - [ ] I have tested this change locally
            - [ ] I have updated the documentation (if needed)
            - [ ] I have added necessary unit tests (if needed)
            - [ ] I have followed the project’s coding style
            - [ ] I have run spotless checks and it passed
            
            ## 💬 Additional context
            
              <!-- Add any other context or screenshots if relevant -->
            `.trim();

            // Fetch the current PR body
            const { data: pr } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: prNumber,
            });

            // Check if template already exists
            const alreadyPresent = pr.body && pr.body.toLowerCase().includes("## 📌 what does this pr do?");
            if (!alreadyPresent) {
              const updatedBody = `${pr.body || ''}\n\n---\n\n${template}`;
              await github.rest.pulls.update({
                owner,
                repo,
                pull_number: prNumber,
                body: updatedBody,
              });
              console.log("✅ PR template appended.");
            } else {
              console.log("PR template already present. Skipping append.");
            }